feat/emoji-with-instant-update
townhall-gov/townhall pull request #119
Opened 2023-09-06 11:09 UTC by Hitesh-gurnani

2023-09-07 11:14 UTC, Hitesh-gurnani commented
https://github.com/townhall-gov/townhall/assets/55234408/9e1532b6-0dce-4df7-a3d3-354feb0b5ef3

2023-09-20 01:04 UTC, This-Is-Prince commented
# Slack emoji design

<img width="363" alt="Screenshot 2023-09-20 at 6 32 54 AM" src="https://github.com/townhall-gov/townhall/assets/89686019/6481576b-b966-422c-8853-16c88511cae2">

# Townhall emoji design

<img width="474" alt="Screenshot 2023-09-20 at 6 33 08 AM" src="https://github.com/townhall-gov/townhall/assets/89686019/05b64335-c404-4259-90bc-86158f4c3773">


why there is no space between `count` and `emoji`?

2023-09-20 01:07 UTC, This-Is-Prince commented
Emoji reaction flow working randomly

[reaction.webm](https://github.com/townhall-gov/townhall/assets/89686019/0ff31b2e-fd5c-4bda-9e52-f1f9108d0606)

2023-09-20 01:15 UTC, This-Is-Prince commented
Reacted by color

<img width="255" alt="image" src="https://github.com/townhall-gov/townhall/assets/89686019/96d0731a-5255-4984-ac77-b0f3eec62650">

2023-09-20 01:33 UTC, This-Is-Prince requested changes
Please test properly, now reaction feature completely broke

2023-09-20 01:33 UTC, This-Is-Prince commented on pages/api/posts/index.ts
> +							[EReaction.LIKE]: data?.reactions_count?.[EReaction.LIKE] || 0,
Please use syntax like
`const reactions_count = getDefaultReactions();`
`Object.values(EReaction).forEach((reaction) => {`
     `if (data.reactions_count?.[reaction]) {`
            `reactions_count[reaction] = data.reactions_count[reaction];`
     `}`
`});`

2023-09-20 01:33 UTC, This-Is-Prince commented on src/ui-components/EmojiTooltip.tsx
> +			<span className='cursor-pointer'>
Is there any specific reason to use extra `span`?

2023-09-20 01:33 UTC, This-Is-Prince commented on src/ui-components/EmojiTooltip.tsx
> +		<Button key={emoji} className='cursor-pointer p-0 bg-transparent border-none text-xl hover:bg-white' onClick={() => onClick(emoji)}>{emoji}</Button>
code is not formatted correctly
<Button
key
className
onClick
/>

2023-09-20 01:33 UTC, This-Is-Prince commented on src/components/Room/Post/ContentWrapper/Content/Reactions/index.tsx
> +			<EmojiCounts
Please use `for loop` for rendering the multiple EmojiCounts component

2023-09-20 01:33 UTC, This-Is-Prince commented on src/components/Room/Post/ContentWrapper/Content/Reactions/index.tsx
> +			if (reaction.type==type && reaction.user.id==user.id) {
Please use user `address`

2023-09-20 01:33 UTC, This-Is-Prince commented on src/components/Room/Post/ContentWrapper/Content/Reactions/index.tsx
>  					const error = 'Something went wrong, unable to give a reaction to post.';
If error comes why you are not removing reaction from reactions array.

2023-09-20 01:33 UTC, This-Is-Prince commented on src/components/Room/Post/ContentWrapper/Content/Reactions/index.tsx
> +					// dispatch(postActions.setReaction(data));
Please set valid document again

2023-09-20 01:33 UTC, This-Is-Prince commented on src/ui-components/EmojiCounts.tsx
> +		<div style={{  maxHeight: '100px', minWidth:'200px', overflowY: 'auto' }}>
I think we can use tailwindcss classes here.
This div is not required

2023-09-20 01:33 UTC, This-Is-Prince commented on src/ui-components/EmojiCounts.tsx
> +					: <p>No reactions found</p>
If there is no reactions why you are rendering this component (Very Bad practice)

2023-09-20 01:33 UTC, This-Is-Prince commented on src/ui-components/EmojiCounts.tsx
> +					classNames(`${count<=0?'hidden':''} flex text-white border border-solid border-blue_primary rounded-2xl py-0.5 hover:bg-blue_primary px-2 font-medium text-sm  ${findUser?'bg-blue_primary':'bg-tr
Don't use hidden, instead if reactions is not found don't render this component

2023-09-20 01:33 UTC, This-Is-Prince commented on src/components/Room/Post/ContentWrapper/CommentsWrapper/Comments/Comment/RepliesWrapper/Replies/Reply/Footer/Reactions/index.tsx
> +			<EmojiCounts
Please check post files comment

2023-09-20 01:33 UTC, This-Is-Prince commented on src/components/Room/Post/ContentWrapper/CommentsWrapper/Comments/Comment/Footer/Reactions/index.tsx
> +			<EmojiCounts
Please check post files comment

2023-09-20 01:33 UTC, This-Is-Prince commented on src/components/Room/Post/ContentWrapper/CommentsWrapper/Comments/Comment/Footer/Reactions/index.tsx
> +		let isDeleted=false;
Can you please create a custom function for this, you are using same code 3 times.

2023-09-20 04:17 UTC, Hitesh-gurnani commented
> Emoji reaction flow working randomly
> 
>  reaction.webm

This itself is the required output

2023-09-20 05:58 UTC, Hitesh-gurnani commented on src/components/Room/Post/ContentWrapper/CommentsWrapper/Comments/Comment/Footer/Reactions/index.tsx
> +		let isDeleted=false;
```
const getIsDeletedField = (reactions: IReactionWithUser[],type:EReaction,user:IUserInfo) => {
	let isDisabled:boolean=false;
	reactions.map((reaction) => {
		if (reaction.type==type && reaction.user.address==user.address) {
			isDisabled=true;
		}
	},[]);
	return isDisabled;
};
```

2023-09-20 06:13 UTC, Hitesh-gurnani commented on src/ui-components/EmojiTooltip.tsx
> +			<span className='cursor-pointer'>
`<AddEmojiReactionIcon className='text-xl cursor-pointer text-blue_primary'/>`

2023-09-20 06:14 UTC, Hitesh-gurnani commented on src/ui-components/EmojiTooltip.tsx
> +		<Button key={emoji} className='cursor-pointer p-0 bg-transparent border-none text-xl hover:bg-white' onClick={() => onClick(emoji)}>{emoji}</Button>
```
const formattedItemList = Object.values(EReaction).map((emoji) => (
		<Button
			key={emoji}
			className='cursor-pointer p-0 bg-transparent border-none text-xl hover:bg-white'
			onClick={() => onClick(emoji)}
		>
			{emoji}
		</Button>
	));
```

2023-09-20 06:16 UTC, Hitesh-gurnani commented on src/components/Room/Post/ContentWrapper/Content/Reactions/index.tsx
> +			if (reaction.type==type && reaction.user.id==user.id) {
```
const getIsDeletedField = (reactions: IReactionWithUser[],type:EReaction,user:IUserInfo) => {
	let isDisabled:boolean=false;
	reactions.map((reaction) => {
		if (reaction.type==type && reaction.user.address==user.address) {
			isDisabled=true;
		}
	},[]);
	return isDisabled;
};
```

2023-09-20 06:19 UTC, Hitesh-gurnani commented on src/ui-components/EmojiCounts.tsx
> +		<div style={{  maxHeight: '100px', minWidth:'200px', overflowY: 'auto' }}>
`<div className='min-h-[100px] min-w-[200px] overflow-y-auto'>`

2023-09-20 06:53 UTC, Hitesh-gurnani commented on src/components/Room/Post/ContentWrapper/CommentsWrapper/Comments/Comment/RepliesWrapper/Replies/Reply/Footer/Reactions/index.tsx
> +			<EmojiCounts
```
const reactionsTypes = useCommentReactions(reactions);

{
				reactionsTypes.map((reaction,idx) => {
					return (
						<EmojiCounts
							key={idx}
							count={reaction.reactionType.length || 0}
							loading={loading}
							onClick={onReaction}
							type={reaction.type}
							userReaction={userReaction}
							reactions={reaction.reactionType}
						/>
					);
				})
			}
```

```
const useCommentReactions = (reactions: IReactionWithUser[]) => {
	const clapReactions: IReactionWithUser[] = [];
	const dislikeReactions: IReactionWithUser[] = [];
	const happyReactions: IReactionWithUser[] = [];
	const heartReactions: IReactionWithUser[] = [];
	const likeReactions: IReactionWithUser[] = [];
	const powerReactions: IReactionWithUser[] = [];
	if (reactions && Array.isArray(reactions)) {
		reactions.forEach((reaction) => {
			if (reaction.type === EReaction.CLAP) {
				clapReactions.push(reaction);
			}
			else if (reaction.type === EReaction.DISLIKE) {
				dislikeReactions.push(reaction);
			}
			else if (reaction.type === EReaction.HAPPY) {
				happyReactions.push(reaction);
			}
			else if (reaction.type === EReaction.HEART) {
				heartReactions.push(reaction);
			}
			else if (reaction.type === EReaction.LIKE) {
				likeReactions.push(reaction);
			}
			else if (reaction.type === EReaction.POWER) {
				powerReactions.push(reaction);
			}

		});
	}
	return [{ reactionType:clapReactions,type:EReaction.CLAP } , { reactionType:dislikeReactions,type:EReaction.DISLIKE } , { reactionType:happyReactions,type:EReaction.HAPPY } , { reactionType:heartReactions,type:EReaction.HEART } , { reactionType:likeReactions,type:EReaction.LIKE } , { reactionType:powerReactions,type:EReaction.POWER }];
};
```

2023-09-20 07:04 UTC, Hitesh-gurnani commented on src/ui-components/EmojiCounts.tsx
> +					: <p>No reactions found</p>
```
const content = (
		<div className="min-h-[100px] min-w-[200px] overflow-y-auto">
			{reactions && reactions.length > 0 && (
				<ul className="flex flex-col w-full justify-center gap-y-3 mt-3">
					{reactions.map((reaction) => (
						<li key={reaction.id} className="list-none">
							<UserInfo
								user_info={reaction.user}
								addressProps={{
									className: 'text-grey_tertiary font-medium text-base leading-[20px] tracking-[0.01em]',
									ethIdenticonSize: 20,
									identiconSize: 20
								}}
							/>
						</li>
					))}
				</ul>
			)}
		</div>
	);
```

2023-09-20 07:11 UTC, Hitesh-gurnani commented on src/components/Room/Post/ContentWrapper/Content/Reactions/index.tsx
> +			<EmojiCounts
```
{
				reactionsTypes.map((reaction,idx) => {
					return (
						<EmojiCounts
							key={idx}
							count={reaction.reactionType.length || 0}
							loading={loading}
							onClick={onReaction}
							type={reaction.type}
							userReaction={userReaction}
							reactions={reaction.reactionType}
						/>
					);
				})
			}
```

2023-09-20 07:21 UTC, Hitesh-gurnani commented on src/ui-components/EmojiCounts.tsx
> +					classNames(`${count<=0?'hidden':''} flex text-white border border-solid border-blue_primary rounded-2xl py-0.5 hover:bg-blue_primary px-2 font-medium text-sm  ${findUser?'bg-blue_primary':'bg-tr
```
{
				reactionsTypes.map((reaction, idx) => (
					reaction.reactionType.length > 0 && (
						<EmojiCounts
							key={idx}
							count={reaction.reactionType.length || 0}
							loading={loading}
							onClick={onReaction}
							type={reaction.type}
							userReaction={userReaction}
							reactions={reaction.reactionType}
						/>
					)
				))
			}
```

2023-09-25 11:00 UTC, closed without merging