Feat/user profile in townhall
townhall-gov/townhall pull request #120
Opened 2023-09-06 21:40 UTC by Hitesh-gurnani

2023-09-20 01:45 UTC, This-Is-Prince commented
I have created more than 50 rooms, but in my profile i'm only able to see 9. There is no modal which can show all the rooms with pagination.

[multiple-created-rooms.webm](https://github.com/townhall-gov/townhall/assets/89686019/5df73f48-a804-4ee9-ace9-0b99e75260c0)


<img width="1147" alt="Screenshot 2023-09-20 at 7 12 49 AM" src="https://github.com/townhall-gov/townhall/assets/89686019/b6ef9b41-c515-4ffb-8ebb-6fd46c4356d5">

2023-09-20 01:48 UTC, This-Is-Prince commented
Getting this error when connecting second account and i'm still in my previous profile page.

<img width="1470" alt="Screenshot 2023-09-20 at 7 17 53 AM" src="https://github.com/townhall-gov/townhall/assets/89686019/9f061e31-db08-4f6b-8905-b3a5d0753bba">

![Screenshot 2023-09-20 at 7 17 53 AM (2)](https://github.com/townhall-gov/townhall/assets/89686019/5bde1fe6-7cc5-40fb-93a4-9f2fe2c32ccc)

2023-09-20 01:57 UTC, This-Is-Prince commented
# There is no proper testing done for this PR

[editprofile-bug.webm](https://github.com/townhall-gov/townhall/assets/89686019/2dbb68c8-7244-45af-81fe-0d58159b622b)

2023-09-20 02:03 UTC, This-Is-Prince requested changes
Please test feature properly

2023-09-20 02:03 UTC, This-Is-Prince commented on src/ui-components/TextEditor/index.tsx
> +`;
Still pending.....

2023-09-21 14:23 UTC, Hitesh-gurnani commented on src/ui-components/UserTooltip.tsx
> +						<Link href={`https://etherscan.io/address/${user_info.address}`} target="_blank">
```
const generateProfileButtons = (user: IUserInfo | null) => {
	if (!user) return null;

	const profileLink = user.address ? `/user/${user.address}` : '';
	const explorerLink = user.address?.startsWith('0x')
		? `https://etherscan.io/address/${user.address}`
		: `https://www.subscan.io/account/${user?.address}`;

	return (
		<div className='flex flex-row justify-between items-center w-full pt-3'>
			{profileLink && (
				<Link href={profileLink}>
					<ViewProfileButton />
				</Link>
			)}
			{explorerLink && (
				<Link href={explorerLink} target="_blank">
					<SeeExplorerButton />
				</Link>
			)}
		</div>
	);
};
```

2023-09-21 14:31 UTC, Hitesh-gurnani commented on src/ui-components/UserTooltip.tsx
> +							<div className='flex  flex-col px-8 justify-center items-center  w-[240px]'>
```
{user.img_url ? (
						<Image preview={false} width={user.username ? 75 : 90} height={user.username ? 75 : 90} className='rounded-full'
							src={user.img_url} alt={user.name as string} />
					) : (
						<div className='flex items-center'>
							{!disableIdenticon && (
								<div className='flex items-center justify-center'>
									{address.startsWith('0x') ? (
										<EthIdenticon className='flex items-center justify-center' size={60} address={address} />
									) : (
										<Identicon className='flex items-center justify-center' value={address} size={60} theme={'polkadot'} />
									)}
								</div>
							)}
						</div>
					)}
```

2023-10-04 07:50 UTC, closed without merging